services:
  python:
    build: ./python
    container_name: "python"
    ports:
      - "8000:8000"
    volumes:
      - ./python:/work
      - ./easyocr_models:/root/.EasyOCR
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1