spring:
  application:
    name: mars_king
  cloud:
    openfeign:
      client:
        config:
          pythonClient: # @FeignClient name
            connectTimeout: 5000
            readTimeout: 30000
mvc:
  throw-exception-if-no-handler-found: true #ExceptionHandler에서 예외 탐색
#web:
#  resource:
#    add-mappings: false
server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true